import type { Metadata } from "next";
import { quicksand } from "./fonts";
import Footer from "./footer";
import "./global.scss";
import Header from "./header";
import styles from "./layout.module.scss";
import ScrollToTop from "./scrollToTop";

export const metadata: Metadata = {
  title: "Zek music",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <div id={styles.superContainer} className={quicksand.className}>
          <Header />
          <main>{children}</main>
          <Footer />
        </div>
        <ScrollToTop />
      </body>
    </html>
  );
}
